---
- name: Deploy Proxmox VM with Terraform
  hosts: localhost
  gather_facts: true
  roles:
    - infrastructure
  tags: [infra]

- name: Wait for VM SSH to be ready
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait for SSH on VM
      ansible.builtin.wait_for:
        host: "{{ hostvars['master']['ansible_host'] }}"
        port: 22
        timeout: 300
        delay: 5
        state: started
  tags: [wait]

- name: Configure Kubernetes Master Node
  hosts: master
  gather_facts: true
  become: true
  roles:
    - master_node
  tags: [configure]

- name: Wait for SSH on all k8s nodes
  hosts: k8s_workers
  gather_facts: false
  tasks:
    - name: Wait for SSH to be available
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 22
        state: started
        timeout: 300
        delay: 5
      delegate_to: localhost
      run_once: false
  tags: [wait]

- name: Join worker nodes to the Kubernetes cluster
  hosts: k8s_workers
  become: true
  gather_facts: false
  roles:
    - worker_nodes
  tags: [configure]